version: "3.8"

services:
  app:
    build: .
    ports:
      - "1234:1234"
    volumes:
      - timesheesh_data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/prod.db
      - JWT_SECRET=local_development_jwt_secret_key_123
    restart: unless-stopped

volumes:
  timesheesh_data:
