version: "3.8"

services:
  app:
    build: .
    ports:
      - "1234:1234"
    volumes:
      - timesheesh_data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data/prod.db
    restart: unless-stopped

volumes:
  timesheesh_data:
