name: Auto approve and merge release PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
